#!/bin/bash
echo "This is a simple script for resetting of password for Teamviewer....Feel free to add your comment"
teamviewer info
echo "Input your new password"
read newpass
sudo teamviewer passwd $newpass
echo "Password reset done"
